@echo off

rem SET ASYNC_MODE_THREADING=y
rem SET ENABLE_MONKEY_PATCH_ALL=y

SET ORACLE_USER='sys'
SET ORACLE_PASS="Oradoc_db1"
SET ORACLE_HOST='localhost'
SET ORACLE_PORT=1521
SET ORACLE_SERVICE_NAME='ORCLCDB.localdomain'
SET ORACLE_SID='ORCLPDB1.localdomain'

rem SET MSSQL_USE_DSN=Y
SET MSSQL_DSN=localmssql
SET "MSSQL_DRIVER=ODBC Driver 17 for SQL Server"
SET MSSQL_USER=sa
SET "MSSQL_PASS=Strong!Passw0rd"
SET MSSQL_HOST=192.168.1.136
SET MSSQL_CATALOG=tempdb
rem SET MSSQL_USE_CUSTOM_EVENTLET_POOL_CREATOR=y

SET PSQL_USER='postgres'
SET PSQL_PASS='mysecretpass'
SET PSQL_HOST='localhost'
SET PSQL_PORT=5432
SET PSQL_SCHEMA='postgres'

SET FLASK_ENV=development
SET FLASK_HOST=0.0.0.0
SET FLASK_APP=app.py

pipenv run python app.py